/*
 * 10_telecom_network_graph.sql
 * Dedicated Seer Comms subscriber and network impact property graph.
 */

SET SERVEROUTPUT ON
PROMPT Creating Seer Comms telecom network graph schema...

BEGIN
    EXECUTE IMMEDIATE 'DROP PROPERTY GRAPH telecom_experience_network';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-942, -4043) THEN
            DBMS_OUTPUT.PUT_LINE('Skipping telecom_experience_network drop: ' || SQLERRM);
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE telecom_case_entities CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE telecom_graph_relationships CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE telecom_experience_cases CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE telecom_graph_entities CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE telecom_graph_entities (
  entity_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  entity_key       VARCHAR2(80) NOT NULL UNIQUE,
  display_name     VARCHAR2(180) NOT NULL,
  entity_type      VARCHAR2(40) NOT NULL
                   CHECK (entity_type IN (
                     'subscriber','enterprise_account','service_line','network_site',
                     'outage_event','support_case','device','field_crew',
                     'account_advocate','capacity_pool','case_anchor'
                   )),
  region           VARCHAR2(80),
  city             VARCHAR2(80),
  risk_score       NUMBER(5,2) DEFAULT 0 NOT NULL,
  experience_score NUMBER(5,2) DEFAULT 0 NOT NULL,
  affected_count   NUMBER(10) DEFAULT 0 NOT NULL,
  signal_count     NUMBER(8) DEFAULT 0 NOT NULL,
  service_value    NUMBER(14,2) DEFAULT 0 NOT NULL,
  first_seen       TIMESTAMP DEFAULT SYSTIMESTAMP,
  last_seen        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_telecom_graph_entity_type ON telecom_graph_entities(entity_type);
CREATE INDEX idx_telecom_graph_risk ON telecom_graph_entities(risk_score DESC);
CREATE INDEX idx_telecom_graph_region ON telecom_graph_entities(region);

CREATE TABLE telecom_graph_relationships (
  relationship_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  from_entity       NUMBER NOT NULL REFERENCES telecom_graph_entities(entity_id),
  to_entity         NUMBER NOT NULL REFERENCES telecom_graph_entities(entity_id),
  relationship_type VARCHAR2(50) NOT NULL
                    CHECK (relationship_type IN (
                      'subscribes_to','served_by','reports_signal','shares_site',
                      'impacted_by','assigned_crew','escalates_case','uses_device',
                      'enterprise_contact','capacity_dependency','same_region',
                      'service_path','churn_risk_link'
                    )),
  strength          NUMBER(4,3) DEFAULT 0.5 NOT NULL,
  event_count       NUMBER(8) DEFAULT 1 NOT NULL,
  affected_count    NUMBER(10) DEFAULT 0 NOT NULL,
  first_seen        TIMESTAMP DEFAULT SYSTIMESTAMP,
  last_seen         TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT uq_telecom_graph_rel UNIQUE (from_entity, to_entity, relationship_type)
);

CREATE INDEX idx_telecom_rel_from ON telecom_graph_relationships(from_entity);
CREATE INDEX idx_telecom_rel_to ON telecom_graph_relationships(to_entity);
CREATE INDEX idx_telecom_rel_type ON telecom_graph_relationships(relationship_type);

CREATE TABLE telecom_experience_cases (
  case_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  case_ref          VARCHAR2(80) NOT NULL UNIQUE,
  case_type         VARCHAR2(80) NOT NULL,
  case_status       VARCHAR2(40) DEFAULT 'investigating' NOT NULL
                    CHECK (case_status IN ('investigating','escalated','routed','monitoring','closed')),
  priority          VARCHAR2(20) DEFAULT 'medium' NOT NULL
                    CHECK (priority IN ('critical','high','medium','low')),
  risk_score        NUMBER(5,2) DEFAULT 0 NOT NULL,
  subscribers_affected NUMBER(10) DEFAULT 0 NOT NULL,
  service_value_at_risk NUMBER(14,2) DEFAULT 0 NOT NULL,
  opened_at         TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE telecom_case_entities (
  case_entity_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  case_id        NUMBER NOT NULL REFERENCES telecom_experience_cases(case_id),
  entity_id      NUMBER NOT NULL REFERENCES telecom_graph_entities(entity_id),
  role_in_case   VARCHAR2(50) NOT NULL
                 CHECK (role_in_case IN ('seed_signal','affected_account','network_site','service_line','assigned_crew','support_case','subscriber_cluster','case_anchor')),
  confidence     NUMBER(4,3) DEFAULT 0.75 NOT NULL,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT uq_telecom_case_entity UNIQUE (case_id, entity_id, role_in_case)
);

CREATE INDEX idx_telecom_case_entity_case ON telecom_case_entities(case_id);
CREATE INDEX idx_telecom_case_entity_entity ON telecom_case_entities(entity_id);

CREATE PROPERTY GRAPH telecom_experience_network
  VERTEX TABLES (
    telecom_graph_entities KEY (entity_id)
      LABEL entity
      PROPERTIES (
        entity_id, entity_key, display_name, entity_type, region, city,
        risk_score, experience_score, affected_count, signal_count,
        service_value, first_seen, last_seen
      ),
    telecom_experience_cases KEY (case_id)
      LABEL experience_case
      PROPERTIES (
        case_id, case_ref, case_type, case_status, priority,
        risk_score, subscribers_affected, service_value_at_risk,
        opened_at, updated_at
      )
  )
  EDGE TABLES (
    telecom_graph_relationships KEY (relationship_id)
      SOURCE KEY (from_entity) REFERENCES telecom_graph_entities (entity_id)
      DESTINATION KEY (to_entity) REFERENCES telecom_graph_entities (entity_id)
      LABEL related_to
      PROPERTIES (relationship_id, relationship_type, strength, event_count, affected_count, first_seen, last_seen),
    telecom_case_entities KEY (case_entity_id)
      SOURCE KEY (case_id) REFERENCES telecom_experience_cases (case_id)
      DESTINATION KEY (entity_id) REFERENCES telecom_graph_entities (entity_id)
      LABEL case_involves
      PROPERTIES (case_entity_id, role_in_case, confidence, created_at)
  );

COMMENT ON TABLE telecom_graph_entities IS
  'Seer Comms domain graph vertices for subscribers, service lines, network sites, outage events, support cases, devices, field crews, and account advocates.';
COMMENT ON TABLE telecom_graph_relationships IS
  'Seer Comms graph edges for subscriber impact propagation, capacity dependencies, service paths, and escalation links.';
COMMENT ON TABLE telecom_experience_cases IS
  'Seer Comms network-experience cases such as outages, capacity pressure, roaming surges, activation backlogs, and churn-risk investigations.';
COMMENT ON TABLE telecom_case_entities IS
  'Case-to-entity links that connect telecom experience cases to the affected accounts, sites, service lines, and field teams.';

COMMIT;

SELECT 'Telecom property graph schema ready' AS status FROM dual;
