apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: telco-native-app
    newName: REPLACE_REGION.ocir.io/REPLACE_NAMESPACE/telco-native
    newTag: REPLACE_TAG
