apiVersion: v1
kind: Secret
metadata:
  name: telco-native-runtime
  namespace: telco-native
type: Opaque
stringData:
  APP_SCHEMA_PASSWORD: REPLACE_WITH_DATABASE_PASSWORD
  ORACLE_WALLET_PASSWORD: REPLACE_WITH_WALLET_PASSWORD
  OCI_GENAI_API_KEY: REPLACE_WITH_GENAI_API_KEY
