apiVersion: v1
kind: Service
metadata:
  name: telco-native
  namespace: telco-native
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: telco-native
  ports:
    - name: http
      port: 80
      targetPort: http
